export default {
  APP_SETTINGS: {
    MUSIC_STOP_SPEED: 500,
    MUSIC_VOLUME_CHANGE_SPEED: 100,
  },
  CALLBACKS: {
    STORE_EVENT: 'STORE_EVENT',
    AJAX_EVENT: 'AJAX_EVENT',
  },
  ACTIONS: {
    START: 'START',
    ADD_DATA: 'ADD_DATA',
    REQUEST_STARTED: 'REQUEST_STARTED',
    REQUEST_FINISHED: 'REQUEST_FINISHED',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_FAIL: 'GET_DATA_FAIL',
  },
  DISPATCHER: {
    MAIN: 'VIEW_ACTION',
  },
  ERRORS: {
    NETWORK: 'Network error',
    CONFLICT: 'Conflict error',
  },
  SOUNDS: {
    BUTTON_CLICK: 'BUTTON_CLICK',
    SWITCH_CLICK: 'SWITCH_CLICK',
  },
  MUSIC: {
    MENU_MUSIC: 'MENU_MUSIC',
    GAME_MUSIC: 'GAME_MUSIC',
    GLOBAL_PAUSE_MUSIC: 'GLOBAL_PAUSE_MUSIC',
    GLOBAL_PLAY_MUSIC: 'GLOBAL_PLAY_MUSIC',
    GLOBAL_LOOP_MUSIC: 'GLOBAL_LOOP_MUSIC',
    GLOBAL_VOLUME_MUSIC: 'GLOBAL_VOLUME_MUSIC',
  },
};
